### ISSUE TITLE
Set Session.Timeout in runtime

### ISSUE THREAD

**Issue by tulis** [TheCloudlessSky/Harbour.RedisSessionStateStore#26]
Hi,

I was trying to set the Session.Timeout in runtime, however the timeout has always being reset to the default timeout. The default timeout is taken from the web.config. Based on your code, it seems like the culprit is that the timeout is set to default in ReleaseItemExclusive.
```
        public override void ReleaseItemExclusive(HttpContext context, string id, object lockId)
        {
            using (var client = GetClient())
            {
                UpdateSessionStateIfLocked(client, id, (int)lockId, state =>
                {
                    state.Locked = false;
                    state.Timeout = sessionTimeoutMinutes;
                });
            }
        }
```
Is there any reason why the session timeout is set to default value? Or, I could miss something.

**Comment by TheCloudlessSky** [comment]
Hey @tulis,

I was unaware of setting the `Session.Timeout` through code. But, I can definitely add support for this. Do you know if it's guaranteed to be the same value as set in the `web.config` if it's not changed?

PS - You may also want to consider switching to [Microsoft's Redis SessionStateProvider](https://msdn.microsoft.com/en-us/library/azure/dn690522.aspx).

**Comment by tulis** [comment]
Hi @TheCloudlessSky,

I have run some testing and it is shown that if the `timeout` is not being changed in runtime, it will be set to the same value as set in the `web.config`.

I have taken a look on Microsoft's version, but there is a case that I really need and as of now they are not supporting it.

**Comment by TheCloudlessSky** [comment]
Ok, thanks! I've pushed `1.4.0` that uses `HttpContext.Session.Timeout` instead of always using the web.config's value.
