### ISSUE TITLE
“System.NullReferenceException”

### ISSUE THREAD

**Issue by wangbao618** [TheCloudlessSky/Harbour.RedisSessionStateStore#28]
“System.NullReferenceException” in Harbour.RedisSessionStateStore.dll
i use the redis-server 2.8,and configure my web.config the same as readme.md
RedisSessionStateStoreProvider.cs
public override void ReleaseItemExclusive(HttpContext context, string id, object lockId)
        {
            using (var client = GetClient())
            {
                UpdateSessionStateIfLocked(client, id, (int)lockId, state =>
                {
                    state.Locked = false;
                    state.Timeout = context.Session.Timeout;
                });
            }
        }
i fount the context.Session.Timeout is null

**Comment by TheCloudlessSky** [comment]
Hey @wangbao618. This was already reported in #23. Care to check that out and help investigate why the session would be null? For the time being you can downgrade to 1.3.0.
