### ISSUE TITLE
Always throw NullReferenceException when using this project in asp.net mvc3

### ISSUE THREAD

**Issue by hziee514** [TheCloudlessSky/Harbour.RedisSessionStateStore#29]
I'm trying to use this project in asp.net mvc3, it always throw NullReferenceException when get context.Session.Timeout property, because of the context.Session is not initialized yet at RedisSessionStateStoreProvider.cs:257

**Comment by TheCloudlessSky** [comment]
Hi @hziee514,

See [this comment](https://github.com/TheCloudlessSky/Harbour.RedisSessionStateStore/issues/28#issuecomment-109302163) and #23.
