### ISSUE TITLE
ServiceStack.Text version problem 

### ISSUE THREAD

**Issue by zhouyongtao** [TheCloudlessSky/Harbour.RedisSessionStateStore#30]
PM> Install-Package Harbour.RedisSessionStateStore
正在尝试解析依赖项“ServiceStack.Common (≥ 3.9 && < 4.0)”。
正在尝试解析依赖项“ServiceStack.Text”。
正在尝试解析依赖项“ServiceStack.Redis (≥ 3.9 && < 4.0)”。
正在尝试解析依赖项“ServiceStack.Text (≥ 3.9 && < 4.0)”。
已引用较新版本的“ServiceStack.Text”。

**Comment by TheCloudlessSky** [comment]
See #15 for more info. Thanks!
