### ISSUE TITLE
RedisSessionStateStoreProvider using Sentinels

### ISSUE THREAD

**Issue by hovissimo** [TheCloudlessSky/Harbour.RedisSessionStateStore#31]
As far as I can tell, the RedisSessionStateStoreProvider can't connect to a master based on the get-master-addr-by-name API available from Redis sentinels.

Are there any plans to add sentinel-connection support?

**Comment by TheCloudlessSky** [comment]
Hi @hovissimo,

There aren't any plans to do this as [Microsoft now has their own Redis SessionState provider](https://msdn.microsoft.com/en-us/library/azure/dn690522.aspx). I recommend you take a look at their provider since I'm no longer using session state on any of my projects.

Cheers!
